### ISSUE TITLE
Substitute %ENV in Config.

### ISSUE THREAD

**Issue by svenoe** [RotherOSS/fred#2]
@bschmalhofer - how do I substitute this? https://github.com/RotherOSS/fred/blob/dac41923e8505b49131dd47329e7f9d2a1e7a3ed/Kernel/Config/Files/AAAFred.pm#L38

Kernel::Config is needed in the constructor of Kernel::System::Web::Request, so we would have a dependency loop here... Any ideas? I mod_perl even a thing anymore in 10.1?

**Comment by bschmalhofer** [comment]
@svenoe I'm a bit confused about the whole module, as nothing really deals with configuration. I suppose that using an Autoload Perl package would be an better idea there.

The check itself seems to check whether `Load()` in AAAFred.pm is running in a web context. Thus replacing `$ENV{HTTP_USER_AGENT}` with `$ENV{GATEWAY_INTERFACE}` should do the job. This should work because in _otobo.psgi_ the middleware `$SetSystemEnvMiddleware` is enabled before the middleware `$ManageObjectsMiddleware`.

**Comment by bschmalhofer** [comment]
`$ENV{HTTP_USER_AGENT}` and `$ENV{MOD_PERL}` are no longer checked. Only `$ENV{GATEWAY_INTERFACE}`. Closing this issue.
